export const MintingComingList = [
  {
    id: 1,
    mintingDate: "22.07.27",
    name: "UNI-HUB",
    img: "https://gateway.pinata.cloud/ipfs/QmQrawZQ5Ld5xEaABCUUSDuv1rZVih3RtY4iqy1YgRpML7",
    voteLike: 1024,
    voteUnLike: 2,
    link: "https://cozy-gumdrop-204657.netlify.app/",
  },
  {
    id: 2,
    mintingDate: "22.07.29",
    name: "델리타운",
    img: "http://delitown.net/kmong-delitown/public/img/delitown-new-img02.jpg",
    voteLike: 523,
    voteUnLike: 3,
    link: "http://delitown.net/",
  },
  {
    id: 3,
    mintingDate: "22.07.29",
    name: "닥터 그루트",
    img: "https://drgroot.dogesound.club/static/media/main-groot.277dce7a6eb656332fa1.png",
    voteLike: 490,
    voteUnLike: 6,
    link: "https://drgroot.dogesound.club/",
  },
  {
    id: 4,
    mintingDate: "22.08.04",
    name: "METAPARTY",
    img: "https://cdn.imweb.me/thumbnail/20220720/effb127541608.png",
    voteLike: 33,
    voteUnLike: 6,
    link: "https://themetakongz.com/kr.html",
  },
];
