export const TopNFTProjectLists = [
  {
    id: 1,
    ranking: 1,
    name: "META KONGZ",
    img: "https://lh3.googleusercontent.com/AX_uuKN-OFhtHXtzw5PJ3K-bGW5tg2svacBEv8xO_ii3UCEo6UTjqec4MiXFGP3gsxPD-p-W0d315pEvIOxG3pKNWfT3G8KvAgIl=s168",
    floorPrice: 13600,
    voteLike: 1024,
    voteUnLike: 2,
    link: "https://themetakongz.com/kr.html",
  },
  {
    id: 2,
    ranking: 2,
    name: "SYLTARE",
    img: "https://lh3.googleusercontent.com/sWsPZIov5KKOPsEJkt2OmwxGEkyQH65YDrZhqaX7I-Ayj-XQRNhdxyXwQniyi0GplXl_CHokEsgDRsGSBPD3P-Efg25_FsTzprq2Yw=s168",
    floorPrice: 6950,
    voteLike: 1024,
    voteUnLike: 2,
    link: "https://puuvillasociety.com/",
  },
  {
    id: 3,
    ranking: 3,
    name: "SUNMIYA",
    img: "https://lh3.googleusercontent.com/UEltltZRWTPLVS05D6KYdo18nEZ7Ba4n8rj_OlDh8mnM3_oWassvQ0VDCqCMHHMDe2MruYUVOHhu5MGBRk40Sg09C-M8z3IIZPD8=s168",
    floorPrice: 2150,
    voteLike: 1024,
    voteUnLike: 2,
    link: "https://sunmiya.club/",
  },

  {
    id: 4,
    ranking: 4,
    name: "SNKRZ",
    img: "https://openseauserdata.com/files/7d1a6b28f6c35d75248fdfd8948a5f5f.png",
    floorPrice: 1700,
    voteLike: 1024,
    voteUnLike: 2,
    link: "https://www.thesnkrz.com/",
  },
  {
    id: 5,
    ranking: 5,
    name: "PUUVILLA",
    img: "https://lh3.googleusercontent.com/FUijC7n5bYq8ED4U4JjPjK2hGGN3E1-Vo7SivGFaDajN9QMsTxZ0AZmq4FiYKFUtzAnW-HACWW_XrgRggKpCX8v82nnDmo9PiZNn6g=w365",
    floorPrice: 400,
    voteLike: 1024,
    voteUnLike: 2,
    link: "https://www.tripcat.art/",
  },

  {
    id: 6,
    ranking: 6,
    name: "Tripcat",
    img: "https://lh3.googleusercontent.com/YS8cnFN06kmZoJFHvEbaZo0SpF9yWSauGOzbpL-tT5bXuYsDQNq_TobBY8meXbtdx8zLievhFK7tnK5Twtf_Is_reL3yQ5XegYLOOSI=s168",
    floorPrice: 14000,
    voteLike: 1024,
    voteUnLike: 2,
    link: "https://themetakongz.com/kr.html",
  },
  {
    id: 7,
    ranking: 7,
    name: "Doge Sound Club",
    img: "https://lh3.googleusercontent.com/GFwdjFVKsdzLH_4l4yb2wriUTpxP13-SfxxCL1zFX-xd2PrsYtjM3ZSsoI_iRBzBeA_0AV-hq3b4M81iuQ5SOzobf92SYViuHDIh=s168",
    floorPrice: 14000,
    voteLike: 1024,
    voteUnLike: 2,
    link: "https://dogesound.club/",
  },
  {
    id: 8,
    ranking: 8,
    name: "Klay city",
    img: "https://lh3.googleusercontent.com/deTMyhaY7MxFisD4JS6bSl1ZzWto_oxe7asa6jaKJ7ge4HgnLttfuW-vgPNDpKNXDOpyvDfb6oHsNSUrcQH6cdJ97N00vRD9GgQOHjE=s168",
    floorPrice: 14000,
    voteLike: 1024,
    voteUnLike: 2,
    link: "https://klaycity.com/",
  },
  {
    id: 9,
    ranking: 9,
    name: "Meta Toy DragonZ",
    img: "https://lh3.googleusercontent.com/02PLvfCkPwgAeWBEmRa0HjdfXAabG4-fE9zIrNmecO2YMJUax-ZzvlkqNzT7w2GS19-9us0eoFWvd7S6O2DrSKdW3DrXVlegY1Hefg=s168",
    floorPrice: 14000,
    voteLike: 1024,
    voteUnLike: 2,
    link: "https://metatoydragonz.io/",
  },
  {
    id: 10,
    ranking: 10,
    name: "LARVA NFT",
    img: "https://larvanft.aniverse.io/_img/sec_nft3.png",
    floorPrice: 14000,
    voteLike: 1024,
    voteUnLike: 2,
    link: "https://larvanft.aniverse.io/",
  },
];
